"""Stub de tipos: contrato público de sorridente.export.exporters."""
import abc
from ..core.models import ChatMessage as ChatMessage, Conversation as Conversation
from .interfaces import ExportedFile as ExportedFile, IConversationExporter as IConversationExporter
from _typeshed import Incomplete
from abc import ABC
from typing import Sequence

AUTHOR_LABEL: dict[str, str]

class BaseExporter(IConversationExporter, ABC, metaclass=abc.ABCMeta):
    VISIBLE_AUTHORS: Incomplete
    def _visible(self, messages: Sequence[ChatMessage]) -> list[ChatMessage]: ...
    @staticmethod
    def _stamp(value: str) -> str: ...
    @staticmethod
    def _author(message: ChatMessage) -> str: ...
    def _basename(self, conversation: Conversation) -> str: ...

class TextExporter(BaseExporter):
    @property
    def format(self) -> str: ...
    @property
    def content_type(self) -> str: ...
    def export(self, conversation: Conversation, messages: Sequence[ChatMessage], clinic_name: str) -> ExportedFile: ...

class MarkdownExporter(BaseExporter):
    @property
    def format(self) -> str: ...
    @property
    def content_type(self) -> str: ...
    def export(self, conversation: Conversation, messages: Sequence[ChatMessage], clinic_name: str) -> ExportedFile: ...

class HtmlExporter(BaseExporter):
    @property
    def format(self) -> str: ...
    @property
    def content_type(self) -> str: ...
    def export(self, conversation: Conversation, messages: Sequence[ChatMessage], clinic_name: str) -> ExportedFile: ...
