"""Stub de tipos: contrato público de sorridente.integrations.base."""
import abc
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

class IntegrationKind(str, Enum):
    INFERENCE_PROVIDER = 'inference_provider'
    MESSAGING_CHANNEL = 'messaging_channel'
    CALENDAR = 'calendar'
    PAYMENT = 'payment'

@dataclass(frozen=True)
class CredentialField:
    key: str
    label: str
    secret: bool = ...
    required: bool = ...
    placeholder: str = ...
    help_text: str = ...
    default: Any = ...
    def to_dict(self) -> dict[str, Any]: ...

@dataclass
class IntegrationStatus:
    key: str
    kind: str
    name: str
    description: str
    configured: bool = ...
    enabled: bool = ...
    running: bool = ...
    detail: str = ...
    last_error: str = ...
    extra: dict[str, Any] = field(default_factory=dict)
    def to_dict(self) -> dict[str, Any]: ...

class IIntegration(ABC, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def key(self) -> str: ...
    @property
    @abstractmethod
    def kind(self) -> IntegrationKind: ...
    @property
    @abstractmethod
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    @abstractmethod
    def credential_fields(self) -> tuple[CredentialField, ...]: ...
    @abstractmethod
    async def configure(self, credentials: dict[str, Any]) -> None: ...
    @abstractmethod
    async def enable(self) -> None: ...
    @abstractmethod
    async def disable(self) -> None: ...
    @abstractmethod
    async def test(self) -> dict[str, Any]: ...
    @abstractmethod
    def status(self) -> IntegrationStatus: ...
    def describe(self) -> dict[str, Any]: ...

class BaseIntegration(IIntegration, ABC, metaclass=abc.ABCMeta):
    _credentials: dict[str, Any]
    _last_error: str
    def __init__(self) -> None: ...
    @property
    def credentials(self) -> dict[str, Any]: ...
    @property
    def last_error(self) -> str: ...
    def _remember(self, credentials: dict[str, Any]) -> None: ...
    def masked_credentials(self) -> dict[str, Any]: ...
    def is_configured(self) -> bool: ...
