"""Stub de tipos: contrato público de sorridente.integrations.inference."""
import abc
from ..core.exceptions import LLMError as LLMError
from ..core.interfaces import ILLMProvider as ILLMProvider
from ..infrastructure.llm import GroqLLMProvider as GroqLLMProvider
from .base import BaseIntegration as BaseIntegration, CredentialField as CredentialField, IntegrationKind as IntegrationKind, IntegrationStatus as IntegrationStatus
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from typing import Any, AsyncIterator, Sequence

class BaseInferenceIntegration(BaseIntegration, ABC, metaclass=abc.ABCMeta):
    @property
    def kind(self) -> IntegrationKind: ...
    @property
    @abstractmethod
    def provider(self) -> ILLMProvider: ...
    @property
    @abstractmethod
    def default_model(self) -> str: ...
    _last_error: Incomplete
    async def test(self) -> dict[str, Any]: ...

class GroqInferenceIntegration(BaseInferenceIntegration):
    KEY: str
    _provider: Incomplete
    _default_model: Incomplete
    _enabled: bool
    def __init__(self, provider: GroqLLMProvider | None = None, default_model: str = 'qwen/qwen3.8-27b') -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def default_model(self) -> str: ...
    @property
    def provider(self) -> ILLMProvider: ...
    @property
    def credential_fields(self) -> tuple[CredentialField, ...]: ...
    async def configure(self, credentials: dict[str, Any]) -> None: ...
    async def enable(self) -> None: ...
    async def disable(self) -> None: ...
    def is_configured(self) -> bool: ...
    def status(self) -> IntegrationStatus: ...

class RoutingLLMProvider(ILLMProvider):
    _resolver: Incomplete
    def __init__(self, resolver: InferenceResolver) -> None: ...
    @property
    def model(self) -> str: ...
    @property
    def configured(self) -> bool: ...
    def _provider(self) -> ILLMProvider: ...
    async def complete(self, messages: Sequence[dict[str, Any]], tools: Sequence[dict[str, Any]] | None = None, temperature: float = 0.3, max_tokens: int = 1024) -> dict[str, Any]: ...
    def stream(self, messages: Sequence[dict[str, Any]], temperature: float = 0.3, max_tokens: int = 1024) -> AsyncIterator[str]: ...

class InferenceResolver(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def active_integration(self) -> BaseInferenceIntegration | None: ...
    def active_provider(self) -> ILLMProvider | None: ...
