"""Stub de tipos: contrato público de sorridente.integrations.registry."""
from ..core.exceptions import NotFoundError as NotFoundError, ValidationError as ValidationError
from ..core.interfaces import ICredentialStore as ICredentialStore
from .base import IIntegration as IIntegration, IntegrationKind as IntegrationKind
from .inference import BaseInferenceIntegration as BaseInferenceIntegration, InferenceResolver as InferenceResolver
from .messaging import BaseChannelIntegration as BaseChannelIntegration
from _typeshed import Incomplete
from typing import Any, Generic, Iterator, TypeVar

logger: Incomplete
T = TypeVar('T', bound=IIntegration)

class BaseIntegrationRegistry(Generic[T]):
    kind: IntegrationKind
    _items: dict[str, T]
    def __init__(self) -> None: ...
    def register(self, integration: T) -> BaseIntegrationRegistry[T]: ...
    def get(self, key: str) -> T: ...
    def find(self, key: str) -> T | None: ...
    def keys(self) -> list[str]: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...

class InferenceRegistry(BaseIntegrationRegistry[BaseInferenceIntegration], InferenceResolver):
    kind: Incomplete
    _active_key: str
    def __init__(self) -> None: ...
    def register(self, integration: BaseInferenceIntegration, *, activate: bool = False) -> InferenceRegistry: ...
    @property
    def active_key(self) -> str: ...
    def active_integration(self) -> BaseInferenceIntegration | None: ...
    def activate(self, key: str) -> BaseInferenceIntegration: ...

class MessagingRegistry(BaseIntegrationRegistry[BaseChannelIntegration]):
    kind: Incomplete
    async def start_enabled(self) -> None: ...
    async def stop_all(self) -> None: ...
    def running(self) -> list[BaseChannelIntegration]: ...

class IntegrationRegistry:
    _credentials: Incomplete
    inference: Incomplete
    messaging: Incomplete
    def __init__(self, credentials: ICredentialStore) -> None: ...
    @property
    def registries(self) -> tuple[BaseIntegrationRegistry[Any], ...]: ...
    def register(self, integration: IIntegration, *, activate: bool = False) -> IntegrationRegistry: ...
    def get(self, key: str) -> IIntegration: ...
    def all(self) -> list[IIntegration]: ...
    async def load_all(self) -> None: ...
    async def save(self, key: str, values: dict[str, Any]) -> IIntegration: ...
    async def enable(self, key: str) -> IIntegration: ...
    async def disable(self, key: str) -> IIntegration: ...
    async def set_active_inference(self, key: str) -> BaseInferenceIntegration: ...
    async def autostart(self) -> None: ...
    async def shutdown(self) -> None: ...
    def describe_all(self) -> list[dict[str, Any]]: ...
    def __iter__(self) -> Iterator[IIntegration]: ...
    def __len__(self) -> int: ...
