"""Stub de tipos: contrato público de sorridente.channels.manager."""
import abc
from ..core.exceptions import NotFoundError as NotFoundError
from ..core.interfaces import IMessagingChannel as IMessagingChannel
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from typing import Any, Iterator

logger: Incomplete

class IChannelManager(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def register(self, channel: IMessagingChannel) -> IChannelManager: ...
    @abstractmethod
    def get(self, channel_type: str) -> IMessagingChannel: ...
    @abstractmethod
    def find(self, channel_type: str) -> IMessagingChannel | None: ...
    @abstractmethod
    async def send(self, channel_type: str, external_id: str, text: str) -> bool: ...
    @abstractmethod
    async def send_document(self, channel_type: str, external_id: str, filename: str, data: bytes, content_type: str = 'text/plain', caption: str = '') -> bool: ...
    @abstractmethod
    async def start(self, channel_type: str) -> None: ...
    @abstractmethod
    async def stop(self, channel_type: str) -> None: ...
    @abstractmethod
    async def stop_all(self) -> None: ...
    @abstractmethod
    def status(self) -> list[dict[str, Any]]: ...

class ChannelManager(IChannelManager):
    _channels: dict[str, IMessagingChannel]
    def __init__(self) -> None: ...
    def register(self, channel: IMessagingChannel) -> ChannelManager: ...
    def get(self, channel_type: str) -> IMessagingChannel: ...
    def find(self, channel_type: str) -> IMessagingChannel | None: ...
    async def send(self, channel_type: str, external_id: str, text: str) -> bool: ...
    async def send_document(self, channel_type: str, external_id: str, filename: str, data: bytes, content_type: str = 'text/plain', caption: str = '') -> bool: ...
    async def start(self, channel_type: str) -> None: ...
    async def stop(self, channel_type: str) -> None: ...
    async def stop_all(self) -> None: ...
    def status(self) -> list[dict[str, Any]]: ...
    def __iter__(self) -> Iterator[IMessagingChannel]: ...
