"""Stub de tipos: contrato público de sorridente.domain.services.interfaces."""
import abc
from ...core.models import Appointment as Appointment, ChatMessage as ChatMessage, ClinicSettings as ClinicSettings, Conversation as Conversation, Dentist as Dentist, FAQ as FAQ, Notification as Notification, Patient as Patient, Procedure as Procedure, User as User
from abc import ABC, abstractmethod
from datetime import date, datetime
from typing import Any

class IService(ABC):
    @property
    def name(self) -> str: ...

class IPatientService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def create(self, **data: Any) -> Patient: ...
    @abstractmethod
    async def update(self, patient_id: str, **data: Any) -> Patient: ...
    @abstractmethod
    async def delete(self, patient_id: str) -> bool: ...
    @abstractmethod
    async def get(self, patient_id: str) -> Patient: ...
    @abstractmethod
    async def list_all(self, search: str = '') -> list[Patient]: ...
    @abstractmethod
    async def get_or_create_by_channel(self, channel: str, external_id: str, name: str) -> Patient: ...

class IDentistService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def create(self, **data: Any) -> Dentist: ...
    @abstractmethod
    async def update(self, dentist_id: str, **data: Any) -> Dentist: ...
    @abstractmethod
    async def delete(self, dentist_id: str) -> bool: ...
    @abstractmethod
    async def get(self, dentist_id: str) -> Dentist: ...
    @abstractmethod
    async def list_all(self, only_active: bool = False) -> list[Dentist]: ...

class IProcedureService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def create(self, **data: Any) -> Procedure: ...
    @abstractmethod
    async def update(self, procedure_id: str, **data: Any) -> Procedure: ...
    @abstractmethod
    async def delete(self, procedure_id: str) -> bool: ...
    @abstractmethod
    async def list_all(self, only_active: bool = False) -> list[Procedure]: ...

class ISchedulingService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def available_slots(self, day: date, dentist_id: str = '', duration_minutes: int = 0) -> list[dict[str, Any]]: ...
    @abstractmethod
    async def is_free(self, dentist_id: str, start: datetime, end: datetime, ignore_id: str = '') -> bool: ...
    @abstractmethod
    async def next_emergency_slot(self, reference: datetime | None = None) -> dict[str, Any]: ...

class IAppointmentService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def schedule(self, patient_id: str, start: datetime, dentist_id: str = '', procedure_id: str = '', notes: str = '', origin: str = 'web', allow_overbook: bool = False, priority: str = 'normal') -> Appointment: ...
    @abstractmethod
    async def schedule_emergency(self, patient_id: str, reason: str, origin: str = 'web', start: datetime | None = None) -> Appointment: ...
    @abstractmethod
    async def reschedule(self, appointment_id: str, start: datetime) -> Appointment: ...
    @abstractmethod
    async def cancel(self, appointment_id: str, reason: str = '') -> Appointment: ...
    @abstractmethod
    async def set_status(self, appointment_id: str, status: str) -> Appointment: ...
    @abstractmethod
    async def get(self, appointment_id: str) -> Appointment: ...
    @abstractmethod
    async def list_all(self, **filters: Any) -> list[Appointment]: ...
    @abstractmethod
    async def agenda(self, start: date, end: date) -> list[Appointment]: ...
    @abstractmethod
    async def due_reminders(self, window_hours: int = 24) -> list[Appointment]: ...
    @abstractmethod
    async def mark_reminder_sent(self, appointment_id: str) -> Appointment: ...

class IConversationService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def get_or_create(self, channel: str, external_id: str, display_name: str = '') -> Conversation: ...
    @abstractmethod
    async def append(self, conversation_id: str, author: str, content: str, **extra: Any) -> ChatMessage: ...
    @abstractmethod
    async def history(self, conversation_id: str, limit: int = 50) -> list[ChatMessage]: ...
    @abstractmethod
    async def list_all(self, limit: int = 100) -> list[Conversation]: ...
    @abstractmethod
    async def mark_read(self, conversation_id: str) -> Conversation: ...
    @abstractmethod
    async def set_handoff(self, conversation_id: str, handoff: bool) -> Conversation: ...
    @abstractmethod
    async def get(self, conversation_id: str) -> Conversation: ...
    @abstractmethod
    async def link_patient(self, conversation_id: str, patient_id: str) -> Conversation: ...
    @abstractmethod
    async def mark_handoff_notice(self, conversation_id: str) -> Conversation: ...
    @abstractmethod
    async def close(self, conversation_id: str, reason: str = '') -> Conversation: ...
    @abstractmethod
    async def reopen(self, conversation_id: str) -> Conversation: ...
    @abstractmethod
    async def idle_conversations(self, minutes: int) -> list[Conversation]: ...

class INotificationService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def notify(self, title: str, message: str, level: str = 'info', **meta: Any) -> Notification: ...
    @abstractmethod
    async def list_all(self, only_unread: bool = False, limit: int = 50) -> list[Notification]: ...
    @abstractmethod
    async def mark_read(self, notification_id: str) -> Notification: ...
    @abstractmethod
    async def mark_all_read(self) -> int: ...

class IFAQService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def create(self, question: str, answer: str, tags: list[str] | None = None) -> FAQ: ...
    @abstractmethod
    async def update(self, faq_id: str, **data: Any) -> FAQ: ...
    @abstractmethod
    async def delete(self, faq_id: str) -> bool: ...
    @abstractmethod
    async def list_all(self) -> list[FAQ]: ...
    @abstractmethod
    async def search(self, term: str, limit: int = 5) -> list[FAQ]: ...

class ISettingsService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def get(self) -> ClinicSettings: ...
    @abstractmethod
    async def update(self, **data: Any) -> ClinicSettings: ...

class IAuthService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def authenticate(self, username: str, password: str) -> tuple[User, str]: ...
    @abstractmethod
    async def register(self, username: str, password: str, role: str, display_name: str = '') -> User: ...
    @abstractmethod
    async def resolve_token(self, token: str) -> User: ...
    @abstractmethod
    async def list_users(self) -> list[User]: ...

class IAnalyticsService(IService, metaclass=abc.ABCMeta):
    @abstractmethod
    async def dashboard(self) -> dict[str, Any]: ...
