"""Stub de tipos: contrato público de sorridente.rag.interfaces."""
import abc
from ..core.models import KnowledgeDocument as KnowledgeDocument
from .documents import Chunk as Chunk, ScoredChunk as ScoredChunk, Vector as Vector
from abc import ABC, abstractmethod
from typing import Any, Iterable, Sequence

class IChunker(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def split(self, document: KnowledgeDocument) -> list[Chunk]: ...

class IEmbedder(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def fit(self, chunks: Sequence[Chunk]) -> None: ...
    @abstractmethod
    def embed(self, text: str) -> Vector: ...
    @property
    @abstractmethod
    def is_fitted(self) -> bool: ...

class IVectorStore(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def index(self, entries: Iterable[tuple[Chunk, Vector]]) -> None: ...
    @abstractmethod
    def clear(self) -> None: ...
    @abstractmethod
    def search(self, query: Vector, limit: int = 5) -> list[ScoredChunk]: ...
    @property
    @abstractmethod
    def chunks(self) -> list[Chunk]: ...
    @abstractmethod
    def __len__(self) -> int: ...

class IRetriever(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    async def retrieve(self, query: str, limit: int = 4) -> list[ScoredChunk]: ...
    @abstractmethod
    async def reindex(self, documents: Sequence[KnowledgeDocument]) -> int: ...

class IKnowledgeService(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    async def create(self, title: str, content: str, tags: list[str] | None = None) -> KnowledgeDocument: ...
    @abstractmethod
    async def update(self, document_id: str, **data: Any) -> KnowledgeDocument: ...
    @abstractmethod
    async def delete(self, document_id: str) -> bool: ...
    @abstractmethod
    async def list_all(self) -> list[KnowledgeDocument]: ...
    @abstractmethod
    async def reindex(self) -> int: ...
    @abstractmethod
    async def search(self, question: str, limit: int = 4) -> list[ScoredChunk]: ...
    @abstractmethod
    async def answer_context(self, question: str, limit: int = 4) -> dict[str, Any]: ...
