"""Stub de tipos: contrato público de sorridente.rag.store."""
from .documents import Chunk as Chunk, ScoredChunk as ScoredChunk, Vector as Vector
from .interfaces import IVectorStore as IVectorStore
from typing import Iterable

class InMemoryVectorStore(IVectorStore):
    _entries: list[tuple[Chunk, Vector]]
    def __init__(self) -> None: ...
    def index(self, entries: Iterable[tuple[Chunk, Vector]]) -> None: ...
    def clear(self) -> None: ...
    def search(self, query: Vector, limit: int = 5) -> list[ScoredChunk]: ...
    @property
    def chunks(self) -> list[Chunk]: ...
    def __len__(self) -> int: ...
