"""Stub de tipos: contrato público de sorridente.agent.base."""
import abc
from ..core.interfaces import AgentContext as AgentContext, ITool as ITool
from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Iterable, Iterator

class BaseTool(ITool, ABC, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def name(self) -> str: ...
    @property
    @abstractmethod
    def description(self) -> str: ...
    @property
    def parameters(self) -> dict[str, Any]: ...
    @abstractmethod
    async def run(self, context: AgentContext, **kwargs: Any) -> Any: ...
    async def execute(self, context: AgentContext, **kwargs: Any) -> Any: ...
    @staticmethod
    def parse_datetime(value: str) -> datetime: ...
    @staticmethod
    def dump(value: Any) -> str: ...

class IToolRegistry(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def register(self, tool: ITool) -> IToolRegistry: ...
    @abstractmethod
    def unregister(self, name: str) -> None: ...
    @abstractmethod
    def get(self, name: str) -> ITool | None: ...
    @abstractmethod
    def schemas(self) -> list[dict[str, Any]]: ...
    @abstractmethod
    def names(self) -> list[str]: ...

class ToolRegistry(IToolRegistry):
    _tools: dict[str, ITool]
    def __init__(self, tools: Iterable[ITool] | None = None) -> None: ...
    def register(self, tool: ITool) -> ToolRegistry: ...
    def unregister(self, name: str) -> None: ...
    def get(self, name: str) -> ITool | None: ...
    def schemas(self) -> list[dict[str, Any]]: ...
    def names(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[ITool]: ...
    def __contains__(self, name: object) -> bool: ...
