"""Stub de tipos: contrato público de sorridente.agent.context."""
import abc
from .models import Model as Model
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Iterator, Sequence

class MessageRole(str, Enum):
    SYSTEM = 'system'
    USER = 'user'
    ASSISTANT = 'assistant'
    TOOL = 'tool'

@dataclass
class PromptMessage:
    role: MessageRole
    content: str = ...
    tool_calls: list[dict[str, Any]] = field(default_factory=list)
    tool_call_id: str = ...
    name: str = ...
    def to_payload(self) -> dict[str, Any]: ...
    @property
    def estimated_tokens(self) -> int: ...

class IContextPolicy(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def apply(self, messages: Sequence[PromptMessage], model: Model) -> list[PromptMessage]: ...

class SlidingWindowPolicy(IContextPolicy):
    _max_messages: Incomplete
    def __init__(self, max_messages: int = 24) -> None: ...
    def apply(self, messages: Sequence[PromptMessage], model: Model) -> list[PromptMessage]: ...

class TokenBudgetPolicy(IContextPolicy):
    _usage_ratio: Incomplete
    _min_messages: Incomplete
    def __init__(self, usage_ratio: float = 0.6, min_messages: int = 4) -> None: ...
    def apply(self, messages: Sequence[PromptMessage], model: Model) -> list[PromptMessage]: ...

class CompositePolicy(IContextPolicy):
    _policies: Incomplete
    def __init__(self, *policies: IContextPolicy) -> None: ...
    def apply(self, messages: Sequence[PromptMessage], model: Model) -> list[PromptMessage]: ...

class ConversationContext:
    _policy: Incomplete
    _messages: list[PromptMessage]
    def __init__(self, system_prompt: str = '', policy: IContextPolicy | None = None) -> None: ...
    def system(self, content: str) -> ConversationContext: ...
    def user(self, content: str) -> ConversationContext: ...
    def assistant(self, content: str, tool_calls: list[dict[str, Any]] | None = None) -> ConversationContext: ...
    def tool_result(self, tool_call_id: str, name: str, content: str) -> ConversationContext: ...
    def extend(self, messages: Sequence[PromptMessage]) -> ConversationContext: ...
    def render(self, model: Model) -> list[dict[str, Any]]: ...
    @property
    def messages(self) -> list[PromptMessage]: ...
    @property
    def estimated_tokens(self) -> int: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[PromptMessage]: ...
