"""Stub de tipos: contrato público de sorridente.agent.models."""
import abc
from abc import ABC, abstractmethod
from dataclasses import dataclass, field as field
from enum import Flag
from typing import Any, Iterator

class Supports(Flag):
    NONE = 0
    TEXT = ...
    TOOLS = ...
    STREAMING = ...
    IMAGE = ...
    AUDIO = ...
    JSON_MODE = ...
    REASONING = ...
    PARALLEL_TOOLS = ...
    def describe(self) -> list[str]: ...

@dataclass(frozen=True)
class Model:
    id: str
    provider: str = ...
    supports: Supports = ...
    context_window: int = ...
    max_output_tokens: int = ...
    display_name: str = ...
    notes: str = ...
    def capable_of(self, capability: Supports) -> bool: ...
    @property
    def name(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

DEFAULT_SUPPORTS: Supports

class IModelCatalog(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def register(self, model: Model) -> IModelCatalog: ...
    @abstractmethod
    def get(self, model_id: str, provider: str = 'groq') -> Model: ...

class ModelCatalog(IModelCatalog):
    _models: dict[str, Model]
    def __init__(self, models: list[Model] | None = None) -> None: ...
    @staticmethod
    def _defaults() -> list[Model]: ...
    def register(self, model: Model) -> ModelCatalog: ...
    def get(self, model_id: str, provider: str = 'groq') -> Model: ...
    def __iter__(self) -> Iterator[Model]: ...
