"""Stub de tipos: contrato público de sorridente.agent.task."""
import abc
import time
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Iterator

class TaskStatus(str, Enum):
    PENDING = 'pending'
    RUNNING = 'running'
    DONE = 'done'
    FAILED = 'failed'
    CANCELLED = 'cancelled'
    @property
    def finished(self) -> bool: ...

class TaskKind(str, Enum):
    CONVERSATION_TURN = 'conversation_turn'
    TOOL_CALL = 'tool_call'
    INFERENCE = 'inference'

@dataclass
class SubTask:
    name: str
    kind: TaskKind = ...
    status: TaskStatus = ...
    arguments: dict[str, Any] = field(default_factory=dict)
    result: Any = ...
    error: str = ...
    id: str = ...
    started_at: float = field(default_factory=time.time)
    finished_at: float | None = ...
    def start(self) -> SubTask: ...
    def complete(self, result: Any = None) -> SubTask: ...
    def fail(self, error: str) -> SubTask: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

@dataclass
class Task:
    conversation_id: str
    prompt: str
    kind: TaskKind = ...
    status: TaskStatus = ...
    subtasks: list[SubTask] = field(default_factory=list)
    answer: str = ...
    error: str = ...
    iterations: int = ...
    id: str = ...
    started_at: float = field(default_factory=time.time)
    finished_at: float | None = ...
    def start(self) -> Task: ...
    def add_subtask(self, name: str, kind: TaskKind = ..., **arguments: Any) -> SubTask: ...
    def complete(self, answer: str) -> Task: ...
    def fail(self, error: str) -> Task: ...
    @property
    def pending_subtasks(self) -> list[SubTask]: ...
    @property
    def failed_subtasks(self) -> list[SubTask]: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

class ITaskTracker(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def track(self, task: Task) -> Task: ...
    @abstractmethod
    def recent(self, limit: int = 50) -> list['Task']: ...
    @abstractmethod
    def by_conversation(self, conversation_id: str) -> list['Task']: ...

class TaskTracker(ITaskTracker):
    _tasks: list[Task]
    _max_size: Incomplete
    def __init__(self, max_size: int = 200) -> None: ...
    def track(self, task: Task) -> Task: ...
    def recent(self, limit: int = 50) -> list[Task]: ...
    def by_conversation(self, conversation_id: str) -> list[Task]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Task]: ...
