"""Stub de tipos: contrato público de sorridente.core.interfaces."""
import abc
from .models import Entity as Entity
from abc import ABC, abstractmethod
from typing import Any, AsyncIterator, Generic, Sequence, TypeVar

T = TypeVar('T', bound=Entity)

class IDatabase(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    async def connect(self) -> None: ...
    @abstractmethod
    async def disconnect(self) -> None: ...
    @abstractmethod
    async def insert(self, table: str, document: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    async def update(self, table: str, doc_id: str, document: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    async def delete(self, table: str, doc_id: str) -> bool: ...
    @abstractmethod
    async def get(self, table: str, doc_id: str) -> dict[str, Any] | None: ...
    @abstractmethod
    async def find(self, table: str, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
    @abstractmethod
    async def all(self, table: str) -> list[dict[str, Any]]: ...
    @abstractmethod
    async def count(self, table: str, filters: dict[str, Any] | None = None) -> int: ...

class IRepository(ABC, Generic[T], metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def table_name(self) -> str: ...
    @abstractmethod
    async def add(self, entity: T) -> T: ...
    @abstractmethod
    async def update(self, entity: T) -> T: ...
    @abstractmethod
    async def remove(self, entity_id: str) -> bool: ...
    @abstractmethod
    async def get(self, entity_id: str) -> T | None: ...
    @abstractmethod
    async def list(self, filters: dict[str, Any] | None = None) -> list[T]: ...

class ICredentialStore(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    async def get(self, key: str, default: Any = None) -> Any: ...
    @abstractmethod
    async def set(self, key: str, value: Any) -> None: ...
    @abstractmethod
    async def all(self) -> dict[str, Any]: ...
    @abstractmethod
    async def delete(self, key: str) -> None: ...

class ILLMProvider(ABC, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def model(self) -> str: ...
    @abstractmethod
    async def complete(self, messages: Sequence[dict[str, Any]], tools: Sequence[dict[str, Any]] | None = None, temperature: float = 0.3, max_tokens: int = 1024) -> dict[str, Any]: ...
    @abstractmethod
    def stream(self, messages: Sequence[dict[str, Any]], temperature: float = 0.3, max_tokens: int = 1024) -> AsyncIterator[str]: ...

class ITool(ABC, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def name(self) -> str: ...
    @property
    @abstractmethod
    def description(self) -> str: ...
    @property
    @abstractmethod
    def parameters(self) -> dict[str, Any]: ...
    @abstractmethod
    async def execute(self, context: AgentContext, **kwargs: Any) -> Any: ...
    def to_schema(self) -> dict[str, Any]: ...

class IAgent(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    async def reply(self, context: AgentContext, user_message: str) -> str: ...

class AgentContext:
    conversation_id: str
    channel: str
    external_id: str
    patient_id: str
    display_name: str
    metadata: dict[str, Any]
    def __init__(self, conversation_id: str, channel: str, external_id: str = '', patient_id: str = '', display_name: str = 'Visitante', metadata: dict[str, Any] | None = None) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class IMessagingChannel(ABC, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def channel_type(self) -> str: ...
    @property
    @abstractmethod
    def is_running(self) -> bool: ...
    @abstractmethod
    async def start(self) -> None: ...
    @abstractmethod
    async def stop(self) -> None: ...
    @abstractmethod
    async def send(self, external_id: str, text: str) -> bool: ...
    @abstractmethod
    async def send_document(self, external_id: str, filename: str, data: bytes, content_type: str = 'text/plain', caption: str = '') -> bool: ...

class IEventBus(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    async def publish(self, event: str, payload: dict[str, Any]) -> None: ...
    @abstractmethod
    def subscribe(self) -> Any: ...
    @abstractmethod
    def unsubscribe(self, queue: Any) -> None: ...
