"""Stub de tipos: contrato público de sorridente.core.models."""
from dataclasses import dataclass, field
from datetime import date as date, datetime, time as time
from enum import Enum
from typing import Any

def new_id() -> str: ...
def now_iso() -> str: ...

class Role(str, Enum):
    CLIENTE = 'cliente'
    GESTOR = 'gestor'
    MEDICO = 'medico'

class SlotType(str, Enum):
    REGULAR = 'regular'
    ENCAIXE = 'encaixe'

class Priority(str, Enum):
    NORMAL = 'normal'
    URGENTE = 'urgente'

class AppointmentStatus(str, Enum):
    AGENDADO = 'agendado'
    CONFIRMADO = 'confirmado'
    CONCLUIDO = 'concluido'
    CANCELADO = 'cancelado'
    FALTOU = 'faltou'

class ChannelType(str, Enum):
    WEB = 'web'
    TELEGRAM = 'telegram'
    WHATSAPP = 'whatsapp'

class MessageAuthor(str, Enum):
    USER = 'user'
    ASSISTANT = 'assistant'
    SYSTEM = 'system'
    TOOL = 'tool'
    HUMAN_AGENT = 'human_agent'

class NotificationLevel(str, Enum):
    INFO = 'info'
    SUCESSO = 'sucesso'
    ALERTA = 'alerta'
    ERRO = 'erro'

@dataclass
class Entity:
    id: str = field(default_factory=new_id)
    created_at: str = field(default_factory=now_iso)
    updated_at: str = field(default_factory=now_iso)
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]): ...
    def touch(self) -> None: ...

@dataclass
class Patient(Entity):
    name: str = ...
    phone: str = ...
    email: str = ...
    birth_date: str = ...
    document: str = ...
    insurance_provider: str = ...
    insurance_card: str = ...
    responsible_name: str = ...
    notes: str = ...
    telegram_id: str = ...
    whatsapp_id: str = ...
    treatment: str = ...
    active: bool = ...

@dataclass
class Dentist(Entity):
    name: str = ...
    cro: str = ...
    specialty: str = ...
    email: str = ...
    phone: str = ...
    color: str = ...
    active: bool = ...
    availability: dict[str, list[list[str]]] = field(default_factory=dict)

@dataclass
class Procedure(Entity):
    name: str = ...
    description: str = ...
    duration_minutes: int = ...
    price: float = ...
    active: bool = ...

@dataclass
class Appointment(Entity):
    patient_id: str = ...
    patient_name: str = ...
    dentist_id: str = ...
    dentist_name: str = ...
    procedure_id: str = ...
    procedure_name: str = ...
    start: str = ...
    end: str = ...
    status: str = ...
    slot_type: str = ...
    priority: str = ...
    notes: str = ...
    origin: str = ...
    reminder_sent: bool = ...
    @property
    def is_encaixe(self) -> bool: ...
    @property
    def is_urgent(self) -> bool: ...
    @property
    def duration_minutes(self) -> int: ...
    @property
    def start_dt(self) -> datetime: ...
    @property
    def end_dt(self) -> datetime: ...

@dataclass
class ChatMessage(Entity):
    conversation_id: str = ...
    author: str = ...
    content: str = ...
    tool_name: str = ...
    tool_payload: dict[str, Any] = field(default_factory=dict)

@dataclass
class Conversation(Entity):
    channel: str = ...
    external_id: str = ...
    patient_id: str = ...
    display_name: str = ...
    last_message_at: str = field(default_factory=now_iso)
    unread_for_staff: int = ...
    handoff: bool = ...
    open: bool = ...
    closed_at: str = ...
    closed_reason: str = ...
    handoff_notice_at: str = ...

@dataclass
class Notification(Entity):
    title: str = ...
    message: str = ...
    level: str = ...
    read: bool = ...
    link: str = ...
    meta: dict[str, Any] = field(default_factory=dict)

@dataclass
class FAQ(Entity):
    question: str = ...
    answer: str = ...
    tags: list[str] = field(default_factory=list)
    active: bool = ...

@dataclass
class KnowledgeDocument(Entity):
    title: str = ...
    content: str = ...
    source: str = ...
    source_id: str = ...
    tags: list[str] = field(default_factory=list)
    active: bool = ...

@dataclass
class ClinicSettings(Entity):
    clinic_name: str = ...
    address: str = ...
    phone: str = ...
    email: str = ...
    opening_hour: str = ...
    closing_hour: str = ...
    lunch_start: str = ...
    lunch_end: str = ...
    working_days: list[int] = ...
    slot_minutes: int = ...
    inactivity_minutes: int = ...
    emergency_slot_minutes: int = ...
    max_emergency_per_day: int = ...
    handoff_notice_cooldown_minutes: int = ...
    persona: str = ...

@dataclass
class User(Entity):
    username: str = ...
    password_hash: str = ...
    role: str = ...
    display_name: str = ...
    linked_id: str = ...
    active: bool = ...
